set vars(WxH)                                "800umx800um"
set vars(blkname)                            "earlgrey_pd_aon"
set vars(depth)                              "3"
set vars(g2module)                           "spec-blk"
set vars(level)                              "2"
set vars(lim/mem)                            "{fakeram45_1024x39 : v01}"
set vars(lim/stdcell)                        "{sky130_fd_sc_hd : v0.0.2} {sky130_fd_sc_hdll : v0.0.2}"
set vars(main_clock)                         "clk_i"
set vars(pagename)                           "earlgrey_pd_aon"
set vars(speed)                              "100MHz"
set vars(subblks)                            "pwrmgr rstmgr clkmgr sysrst_ctrl adc_ctrl aon_timer sensor_ctrl sram_ctrl"
set vars(view)                               "PPA"
