set vars(WxH)                                "150umx150um"
set vars(blkname)                            "adc_ctrl"
set vars(depth)                              "3"
set vars(g2module)                           "spec-blk"
set vars(inst_count)                         "5500"
set vars(level)                              "3"
set vars(lim/stdcell)                        "{sky130_fd_sc_hd : v0.0.2} {sky130_fd_sc_hdll : v0.0.2}"
set vars(main_clock)                         "clk_i"
set vars(pagename)                           "adc_ctrl"
set vars(speed)                              "24MHz"
set vars(view)                               "PPA"
