source $env(G2_ROOT)/tcllib/openlib/openlib.tcl
source setup.tcl
source $fvar(tech_fvar)
set blkname $fvar(blkname)

source script/util/helpers.tcl
source script/util/flow_helpers.tcl


# LEF
read_lef $fvar(tech_lef)
foreach lef $fvar(lefs) {
  read_lef $lef
}


# MMMC: corners and liberty per corner (generated by gen-openroad-task)
source ../init/mmmc.tcl


read_db apr_fplan/out/session.db
#read_libraries
read_sdc -echo ../init/sdc_apr_func/sdc.tcl




foreach layer_adjustment $global_routing_layer_adjustments {
  lassign $layer_adjustment layer adjustment
  set_global_routing_layer_adjustment $layer $adjustment
}
set_routing_layers -signal $global_routing_layers \
  -clock $global_routing_clock_layers
set_macro_extension 2

# Global placement skip IOs
global_placement -density $global_place_density \
  -pad_left $global_place_pad -pad_right $global_place_pad -skip_io

# IO Placement
place_pins -hor_layers $io_placer_hor_layer -ver_layers $io_placer_ver_layer

# Global placement with placed IOs and routability-driven
global_placement -routability_driven -density $global_place_density \
  -pad_left $global_place_pad -pad_right $global_place_pad

# checkpoint
#set global_place_db [make_result_file ${design}_${platform}_global_place.db]
#write_db $global_place_db

################################################################
# Repair max slew/cap/fanout violations and normalize slews
source $fvar(layer_rc)

set_wire_rc -signal -layer $wire_rc_layer
set_wire_rc -clock -layer $wire_rc_layer_clk
set_dont_use $dont_use

estimate_parasitics -placement

repair_design -slew_margin $slew_margin -cap_margin $cap_margin

repair_tie_fanout -separation $tie_separation $tielo_port
repair_tie_fanout -separation $tie_separation $tiehi_port

set_placement_padding -global -left $detail_place_pad -right $detail_place_pad
detailed_placement


g2_openroad_rpt
g2_openroad_out


if {$fvar(sw_exit) eq "1"} {
  exit
}
