source $env(G2_ROOT)/tcllib/openlib/openlib.tcl
source setup.tcl
source $fvar(tech_fvar)

source script/apr_vars.tcl

source script/util/helpers.tcl
source script/util/flow_helpers.tcl
#source script/util/Nangate45.vars.tcl

# LEF
read_lef $fvar(tech_lef)
foreach lef $fvar(lefs) {
  read_lef $lef
}


# MMMC: corners and liberty per corner (generated by gen-openroad-task)
source ../init/mmmc.tcl



#source script/util/common.tcl

set margin_x [expr {($fvar(die_width)  - $fvar(core_width))  / 2.0}]
set margin_y [expr {($fvar(die_height) - $fvar(core_height)) / 2.0}]
set die_area  "0 0 $fvar(die_width) $fvar(die_height)"
set core_area "$margin_x $margin_y [expr {$margin_x + $fvar(core_width)}] [expr {$margin_y + $fvar(core_height)}]"

source setup.tcl
set blkname $fvar(blkname)
source .vars.tcl
set sw_exit [sgvar sw_exit]

read_db apr_init/out/session.db
#read_libraries
read_sdc -echo ../init/sdc_apr_func/sdc.tcl

set_thread_count [cpu_count]
# Temporarily disable sta's threading due to random failures
sta::set_thread_count 1

puts "\n# Init Floorplan\n"
initialize_floorplan -site $site \
  -die_area $die_area \
  -core_area $core_area

puts "\n# Create Tracks\n"
source $fvar(create_tracks)

# remove buffers inserted by synthesis
puts "\n# Remove Buffers\n"
remove_buffers

if [file exist "floorplan/place_macro.tcl"] {
  source floorplan/place_macro.tcl
}

################################################################
# Macro Placement
puts "\n# Macro Placement\n"
if { [have_macros] } {
  lassign $macro_place_halo halo_x halo_y
  set_macro_base_halo $halo_x $halo_y
  rtl_macro_placer -report_directory rpt
}

################################################################
# Tapcell insertion
puts "\n# Tapcell Insertion\n"
eval tapcell $tapcell_args ;# tclint-disable command-args

#################################################################
# Power distribution network insertion
puts "\n# PDN\n"
source $fvar(create_pdn)
pdngen
#puts "\n# check_power_grid\n"
#check_power_grid -net VDD -floorplanning -error_file rpt/pdn_check_VDD.rpt
#check_power_grid -net VSS -floorplanning -error_file rpt/pdn_check_VSS.rpt


puts "\n# Rpt\n"
g2_openroad_rpt
puts "\n# Out\n"
g2_openroad_out


if {$sw_exit eq "1"} {
  exit
}
