set vars(WxH)                                "3200umx3200um"
set vars(blkname)                            "top_earlgrey"
set vars(depth)                              "3"
set vars(g2module)                           "spec-blk"
set vars(level)                              "1"
set vars(lim/mem)                            "{fakeram45_1024x39 : v01}"
set vars(lim/stdcell)                        "{sky130_fd_sc_hd : v0.0.2} {sky130_fd_sc_hdll : v0.0.2}"
set vars(main_clock)                         "clk_i"
set vars(pagename)                           "top_earlgrey"
set vars(speed)                              "100MHz"
set vars(subblks)                            "earlgrey_pd_main earlgrey_pd_aon"
set vars(view)                               "PPA"
