source $env(G2_ROOT)/tcllib/openlib/openlib.tcl
source setup.tcl
source $fvar(tech_fvar)
set blkname $fvar(blkname)

source script/util/helpers.tcl
source script/util/flow_helpers.tcl

# LEF
read_lef $fvar(tech_lef)
foreach lef $fvar(lefs) {
  read_lef $lef
}

# MMMC: corners and liberty per corner (generated by gen-openroad-task)
source ../init/mmmc.tcl

if {[file exist out/session.db]} {
  read_db out/session.db
} else {
  read_db apr_postroute/out/session.db
}

################################################################
# Abstract LEF for use as a hard macro by a parent-level design
write_abstract_lef out/$blkname.lef

################################################################
# Blackbox Verilog stub matching the abstract LEF: same port list/
# direction/width, no body. Multi-bit ports are bit-blasted at the
# BTerm level (one BTerm per bit, e.g. tl_i[15], tl_i[14], ...), so
# group them back into a single vector port declaration by base name.

set block [ord::get_db_block]

array set dir_of {}
array set msb_of {}
array set lsb_of {}
set order {}

foreach bterm [$block getBTerms] {
  set full [$bterm getName]
  set io   [$bterm getIoType]
  if {$io eq "INPUT"} {
    set dir "input"
  } elseif {$io eq "OUTPUT"} {
    set dir "output"
  } else {
    set dir "inout"
  }

  if {[regexp {^(.+)\[(\d+)\]$} $full -> base bit]} {
    set name $base
  } else {
    set name $full
    set bit  -1
  }

  if {![info exists dir_of($name)]} {
    lappend order $name
    set dir_of($name) $dir
    set msb_of($name) $bit
    set lsb_of($name) $bit
  } else {
    if {$bit > $msb_of($name)} { set msb_of($name) $bit }
    if {$bit < $lsb_of($name) || $lsb_of($name) == -1} { set lsb_of($name) $bit }
  }
}

set port_decls {}
foreach name $order {
  set dir $dir_of($name)
  set msb $msb_of($name)
  set lsb $lsb_of($name)
  if {$msb == -1} {
    lappend port_decls "  $dir $name"
  } else {
    lappend port_decls "  $dir \[$msb:0\] $name"
  }
}

set fout [open out/${blkname}_hardmacro_bbox.v w]
puts $fout "// Hard-macro blackbox stub for $blkname — physical implementation"
puts $fout "// provided via out/$blkname.lef (write_abstract_lef). No body:"
puts $fout "// this module is a placement/routing macro, not synthesizable logic."
puts $fout "module $blkname ("
puts $fout [join $port_decls ",\n"]
puts $fout ");"
puts $fout "endmodule"
close $fout

puts "Wrote out/$blkname.lef and out/${blkname}_hardmacro_bbox.v"
