set vars(blkname)                            "spi_device"
set vars(ddm_inputs)                         "sdc_apr_func sdc_apr_shift"
set vars(depth)                              "5"
set vars(eda)                                "openroad"
set vars(g2module)                           "openroad-task"
set vars(keepvars)                           "netlist"
set vars(onoff_input)                        "1"
set vars(onoff_setup)                        "1"
set vars(pagename)                           "init"
set vars(run,start)                          "20260817_104213"
set vars(runlog,date)                        "2026-08-17_10:42"
set vars(runlog,errors)                      "2"
set vars(runlog,sdate)                       "08-17"
set vars(runlog,ww)                          "34.1"
set vars(sw_exit)                            "1"
set vars(task)                               "init"
set vars(view)                               "DDM"
