source $env(G2_ROOT)/tcllib/openlib/openlib.tcl
source setup.tcl
source $fvar(tech_fvar)
set blkname $fvar(blkname)

source script/util/helpers.tcl
source script/util/flow_helpers.tcl

# LEF
read_lef $fvar(tech_lef)
foreach lef $fvar(lefs) {
  read_lef $lef
}

# MMMC: corners and liberty per corner (generated by gen-openroad-task)
source ../init/mmmc.tcl

read_db apr_cts/out/session.db
read_sdc -echo ../init/sdc_apr_func/sdc.tcl

################################################################
# Repair max slew/cap/fanout violations and normalize slews
source $fvar(layer_rc)

set_wire_rc -signal -layer $wire_rc_layer
set_wire_rc -clock -layer $wire_rc_layer_clk
set_dont_use $dont_use

################################################################
# Setup/hold timing repair

set_propagated_clock [all_clocks]

# Global routing is fast enough for the flow regressions.
# It is NOT FAST ENOUGH FOR PRODUCTION USE.
set repair_timing_use_grt_parasitics 0
if { $repair_timing_use_grt_parasitics } {
  # Global route for parasitics - no guide file requied
  global_route -congestion_iterations 100
  estimate_parasitics -global_routing
} else {
  estimate_parasitics -placement
}

repair_timing -skip_gate_cloning

# Post timing repair.
report_worst_slack -min -digits 3
report_worst_slack -max -digits 3
report_tns -digits 3
report_check_types -max_slew -max_capacitance -max_fanout -violators -digits 3

utl::metric "RSZ::worst_slack_min" [sta::worst_slack -min]
utl::metric "RSZ::worst_slack_max" [sta::worst_slack -max]
utl::metric "RSZ::tns_max" [sta::total_negative_slack -max]
utl::metric "RSZ::hold_buffer_count" [rsz::hold_buffer_count]

################################################################
# Detailed Placement

detailed_placement

# Capture utilization before fillers make it 100%
utl::metric "DPL::utilization" [format %.1f [expr [rsz::utilization] * 100]]
utl::metric "DPL::design_area" [sta::format_area [rsz::design_area] 0]

# Static IR drop heatmap
analyze_power_grid -net VDD -voltage_file rpt/VDD_ir.rpt
if {[gui::supported]} {
  gui::set_heatmap IRDrop Net VDD
  gui::set_heatmap IRDrop ShowLegend 1

  set block [ord::get_db_block]
  set die   [$block getDieArea]
  set dbu   [expr {double([$block getDbUnitsPerMicron])}]
  set xlo   [expr {[$die xMin] / $dbu}]
  set ylo   [expr {[$die yMin] / $dbu}]
  set xhi   [expr {[$die xMax] / $dbu}]
  set yhi   [expr {[$die yMax] / $dbu}]
  set dctrl [gui::DisplayControlMap]
  $dctrl set {Heat Maps/IR Drop} 1
  gui::save_image out/static_ir.png $xlo $ylo $xhi $yhi 800 0 $dctrl
  puts "Saved static IR drop heatmap to out/static_ir.png"
} else {
  puts "WARNING: GUI not supported in this OpenROAD build; skipping out/static_ir.png heatmap image"
}

g2_openroad_rpt
g2_openroad_out


if {$fvar(sw_exit) eq "1"} {
  exit
}
