source $env(G2_ROOT)/tcllib/openlib/openlib.tcl
source setup.tcl
source $fvar(tech_fvar)
set blkname $fvar(blkname)

source script/util/helpers.tcl
source script/util/flow_helpers.tcl

# LEF
read_lef $fvar(tech_lef)
foreach lef $fvar(lefs) {
  read_lef $lef
}

# MMMC: corners and liberty per corner (generated by gen-openroad-task)
source ../init/mmmc.tcl

read_db apr_place/out/session.db
read_sdc -echo ../init/sdc_apr_func/sdc.tcl

################################################################
# Clock Tree Synthesis

# Clone clock tree inverters next to register loads
# so cts does not try to buffer the inverted clocks.
# repair_clock_inverters  # SKIPPED: known deterministic OpenROAD segfault

clock_tree_synthesis -root_buf $cts_buffer -buf_list $cts_buffer \
  -sink_clustering_enable \
  -sink_clustering_max_diameter $cts_cluster_diameter

# Under this project's hierarchical link_design -hier flow, TritonCTS's clock-gate
# cloning (used when one ICG's fanout is too spread out for a single tree) names each
# clone "clone_<N>_<original icg name>". In hierarchical mode the original icg's name
# is already a full "<module>/<leaf>" path, so the clone name ends up as
# "clone_<N>_<module>/<leaf>" -- the '/' lands *after* the clone index instead of at
# the front. write_verilog derives instance names by stripping everything up to the
# *last* '/', so every clone's printed name collapses back down to the bare original
# leaf name (e.g. "icg"), producing many instances sharing one name in the same module
# scope. Move the "_clone_<N>" tag to the end of the leaf name instead, so the
# stripped name stays unique.
proc fix_cts_clone_gate_names { } {
  set block [ord::get_db_block]
  set nfixed 0
  foreach inst [$block getInsts] {
    set name [$inst getName]
    if {[regexp {^clone_([0-9]+)_(.+)/([^/]+)$} $name -> idx parent leaf]} {
      set new_name "${parent}/${leaf}_clone_${idx}"
      if {![$inst rename $new_name]} {
        puts "WARNING: could not rename CTS clone instance $name to $new_name\
              (name collision?)"
      } else {
        incr nfixed
      }
    }
  }
  if {$nfixed > 0} {
    puts "Renamed $nfixed CTS clock-gate clone instance(s) to avoid duplicate\
          names in write_verilog output."
  }
}
fix_cts_clone_gate_names

# CTS leaves a long wire from the pad to the clock tree root.
repair_clock_nets

# place clock buffers
detailed_placement

g2_openroad_rpt
g2_openroad_out


if {$fvar(sw_exit) eq "1"} {
  exit
}
