set vars(c1_Count)                           "1"
set vars(c1_Latest)                          "1"
set vars(depth)                              "2"
set vars(g2module)                           "scm-blk"
set vars(pagename)                           "sram_ctrl"
