set vars(WxH)                                "200umx200um"
set vars(blkname)                            "sram_ctrl"
set vars(depth)                              "3"
set vars(g2module)                           "spec-blk"
set vars(inst_count)                         "6000"
set vars(level)                              "3"
set vars(lim/mem)                            "{fakeram45_1024x39 : v01}"
set vars(lim/stdcell)                        "{sky130_fd_sc_hd : v0.0.2} {sky130_fd_sc_hdll : v0.0.2}"
set vars(main_clock)                         "clk_i"
set vars(pagename)                           "sram_ctrl"
set vars(speed)                              "150MHz"
set vars(view)                               "PPA"
