set vars(WxH)                                "3300umx3300um"
set vars(blkname)                            "chip_earlgrey_asic"
set vars(depth)                              "3"
set vars(g2module)                           "spec-blk"
set vars(level)                              "0"
set vars(lim/mem)                            "{fakeram45_1024x39 : v01}"
set vars(lim/stdcell)                        "{sky130_fd_sc_hd : v0.0.2} {sky130_fd_sc_hdll : v0.0.2}"
set vars(main_clock)                         "clk_i"
set vars(pagename)                           "chip_earlgrey_asic"
set vars(speed)                              "100MHz"
set vars(subblks)                            "top_earlgrey"
set vars(view)                               "PPA"
