source $env(G2_ROOT)/tcllib/openlib/openlib.tcl
source setup.tcl

set blkname $fvar(blkname)

source script/util/helpers.tcl
source script/util/flow_helpers.tcl


# LEF
read_lef $fvar(tech_lef)
foreach lef $fvar(lefs) {
  read_lef $lef
}


# MMMC: corners and liberty per corner (generated by gen-openroad-task)
source mmmc.tcl

# Netlist
source read_verilog.tcl
link_design -hier $blkname

# SDC
source read_sdc.tcl

g2_openroad_rpt
g2_openroad_out

if {$fvar(sw_exit) eq "1"} {
  exit
}
