source $env(G2_ROOT)/tcllib/openlib/openlib.tcl
source setup.tcl
source $fvar(tech_fvar)
set blkname $fvar(blkname)

source script/util/helpers.tcl
source script/util/flow_helpers.tcl

# LEF
read_lef $fvar(tech_lef)
foreach lef $fvar(lefs) {
  read_lef $lef
}

# MMMC: corners and liberty per corner (generated by gen-openroad-task)
source ../init/mmmc.tcl

read_db apr_postroute/out/session.db
read_sdc -echo ../init/sdc_apr_func/sdc.tcl

################################################################
# Filler placement

filler_placement $filler_cells
check_placement -verbose

################################################################
# Extraction

#puts $rcx_rules_file
#if { $rcx_rules_file != "" } {
#  define_process_corner -ext_model_index 0 X
#  extract_parasitics -ext_model_file $rcx_rules_file
#
#  write_spef out/$blkname.spef
#
#  read_spef out/$blkname.spef
#} else {
#  # Use global routing based parasitics inlieu of rc extraction
  estimate_parasitics -global_routing
#}

drt::check_drc -output_file rpt/drc.rpt

# Static IR drop heatmap
analyze_power_grid -net VDD -voltage_file rpt/VDD_ir.rpt
if {[gui::supported]} {
  gui::set_heatmap IRDrop Net VDD
  gui::set_heatmap IRDrop ShowLegend 1

  set block [ord::get_db_block]
  set die   [$block getDieArea]
  set dbu   [expr {double([$block getDbUnitsPerMicron])}]
  set xlo   [expr {[$die xMin] / $dbu}]
  set ylo   [expr {[$die yMin] / $dbu}]
  set xhi   [expr {[$die xMax] / $dbu}]
  set yhi   [expr {[$die yMax] / $dbu}]
  set dctrl [gui::DisplayControlMap]
  $dctrl set {Heat Maps/IR Drop} 1
  gui::save_image out/static_ir.png $xlo $ylo $xhi $yhi 800 0 $dctrl
  puts "Saved static IR drop heatmap to out/static_ir.png"
} else {
  puts "WARNING: GUI not supported in this OpenROAD build; skipping out/static_ir.png heatmap image"
}

g2_openroad_rpt
g2_openroad_out

add_global_connection -net VDD -pin_pattern VPWR -inst_pattern {.*} -power
add_global_connection -net VSS -pin_pattern VGND -inst_pattern {.*} -ground
global_connect
write_verilog -include_pwr_gnd out/spm.pnl.v

if {$fvar(sw_exit) eq "1"} {
  exit
}
