set vars(WxH)                                "250umx250um"
set vars(blkname)                            "spi_host"
set vars(depth)                              "3"
set vars(g2module)                           "spec-blk"
set vars(inst_count)                         "4000"
set vars(level)                              "3"
set vars(lim/stdcell)                        "{sky130_fd_sc_hd : v0.0.2} {sky130_fd_sc_hdll : v0.0.2}"
set vars(main_clock)                         "clk_i"
set vars(pagename)                           "spi_host"
set vars(speed)                              "96MHz"
set vars(view)                               "PPA"
