blks/spi_host/spi_host_reg_pkg.sv
blks/spi_host/spi_host_cmd_pkg.sv
blks/spi_host/spi_host_shift_register.sv
blks/spi_host/prim_packer_fifo.sv
blks/spi_host/spi_host_byte_select.sv
blks/spi_host/spi_host_byte_merge.sv
blks/spi_host/prim_buf.sv
blks/spi_host/prim_sec_anchor_buf.sv
blks/spi_host/prim_flop_en.sv
blks/spi_host/prim_util_pkg.sv
blks/spi_host/spi_host_fsm.sv
blks/spi_host/spi_host_core.sv
blks/spi_host/prim_count_pkg.sv
blks/spi_host/prim_flop.sv
blks/spi_host/prim_count.sv
blks/spi_host/prim_fifo_sync_cnt.sv
blks/spi_host/prim_fifo_sync.sv
blks/spi_host/spi_host_command_queue.sv
blks/spi_host/spi_host_data_fifos.sv
blks/spi_host/prim_mubi_pkg.sv
blks/spi_host/prim_onehot_enc.sv
blks/spi_host/prim_onehot_check.sv
blks/spi_host/prim_reg_we_check.sv
blks/spi_host/prim_subreg_pkg.sv
blks/spi_host/prim_subreg_arb.sv
blks/spi_host/prim_subreg.sv
blks/spi_host/prim_subreg_ext.sv
blks/spi_host/prim_secded_inv_64_57_dec.sv
blks/spi_host/prim_secded_inv_39_32_dec.sv
blks/spi_host/prim_secded_pkg.sv
blks/spi_host/top_pkg.sv
blks/spi_host/tlul_pkg.sv
blks/spi_host/tlul_data_integ_dec.sv
blks/spi_host/tlul_cmd_intg_chk.sv
blks/spi_host/tlul_err.sv
blks/spi_host/prim_secded_inv_64_57_enc.sv
blks/spi_host/prim_secded_inv_39_32_enc.sv
blks/spi_host/tlul_data_integ_enc.sv
blks/spi_host/tlul_rsp_intg_gen.sv
blks/spi_host/tlul_adapter_reg.sv
blks/spi_host/tlul_err_resp.sv
blks/spi_host/tlul_fifo_sync.sv
blks/spi_host/tlul_socket_1n.sv
blks/spi_host/top_racl_pkg.sv
blks/spi_host/spi_host_reg_top.sv
blks/spi_host/tlul_request_loopback.sv
blks/spi_host/tlul_adapter_reg_racl.sv
blks/spi_host/tlul_adapter_racl.sv
blks/spi_host/tlul_sram_byte.sv
blks/spi_host/tlul_adapter_sram.sv
blks/spi_host/tlul_adapter_sram_racl.sv
blks/spi_host/spi_host_window.sv
blks/spi_host/prim_alert_pkg.sv
blks/spi_host/prim_cdc_rand_delay.sv
blks/spi_host/prim_flop_2sync.sv
blks/spi_host/prim_xnor2.sv
blks/spi_host/prim_diff_decode.sv
blks/spi_host/prim_sec_anchor_flop.sv
blks/spi_host/prim_alert_sender.sv
blks/spi_host/prim_intr_hw.sv
blks/spi_host/prim_arbiter_fixed.sv
blks/spi_host/prim_racl_error_arb.sv
blks/spi_host/spi_device_reg_pkg.sv
blks/spi_host/spi_device_pkg.sv
blks/spi_host/spi_host.sv
