source $env(G2_ROOT)/tcllib/openlib/openlib.tcl
source setup.tcl
source $fvar(tech_fvar)
set blkname $fvar(blkname)
set design  $fvar(blkname)

source script/util/helpers.tcl
source script/util/flow_helpers.tcl

# LEF
read_lef $fvar(tech_lef)
foreach lef $fvar(lefs) {
  read_lef $lef
}

# MMMC: corners and liberty per corner (generated by gen-openroad-task)
source ../init/mmmc.tcl

read_db apr_route/out/session.db
read_sdc -echo ../init/sdc_apr_func/sdc.tcl

################################################################
# Repair antennas post-GRT

utl::set_metrics_stage "grt__{}"
repair_antennas -iterations 1

check_antennas
utl::clear_metrics_stage
utl::metric "GRT::ANT::errors" [ant::antenna_violation_count]

################################################################
# Detailed routing

set_thread_count 8

# Run pin access for newly inserted diode instances
pin_access

detailed_route -output_drc rpt/route_drc.rpt \
  -output_maze log/maze.log \
  -droute_end_iter 5 \
  -verbose 1

write_guides out/output_guide.mod
set drv_count [detailed_route_num_drvs]
utl::metric "DRT::drv" $drv_count

################################################################
# Repair antennas post-DRT

set repair_antennas_iters 0
utl::set_metrics_stage "drt__repair_antennas__pre_repair__{}"
while { [check_antennas] && $repair_antennas_iters < 5 } {
  utl::set_metrics_stage "drt__repair_antennas__iter_${repair_antennas_iters}__{}"

  repair_antennas

  detailed_route -output_drc rpt/ant_fix_drc.rpt \
    -output_maze log/ant_fix_maze.log \
    -droute_end_iter 5 \
    -verbose 1

  incr repair_antennas_iters
}

utl::set_metrics_stage "drt__{}"
check_antennas

utl::clear_metrics_stage
utl::metric "DRT::ANT::errors" [ant::antenna_violation_count]

if { ![design_is_routed] } {
  error "Design has unrouted nets."
}

drt::check_drc -output_file rpt/drc.rpt

g2_openroad_rpt
g2_openroad_out


if {$fvar(sw_exit) eq "1"} {
  exit
}
