source $env(G2_ROOT)/tcllib/openlib/openlib.tcl
source setup.tcl
source $fvar(tech_fvar)
set blkname $fvar(blkname)
set design  $fvar(blkname)

source script/util/helpers.tcl
source script/util/flow_helpers.tcl

# LEF
read_lef $fvar(tech_lef)
foreach lef $fvar(lefs) {
  read_lef $lef
}

# MMMC: corners and liberty per corner (generated by gen-openroad-task)
source ../init/mmmc.tcl

read_db apr_postcts/out/session.db
read_sdc -echo ../init/sdc_apr_func/sdc.tcl

################################################################
# Global routing

set_thread_count 8

# Promote constant tie-off nets to special nets so TritonRoute skips them.
# Under hierarchical linking (-hier) each module instance keeps its own
# local zero_/one_ tie net instead of sharing one flat top-level net, so
# match by signal type rather than by a fixed top-level name.
set _block [ord::get_db_block]
foreach _net [$_block getNets] {
  set _sigtype [$_net getSigType]
  if {($_sigtype eq "GROUND" || $_sigtype eq "POWER") && ![$_net isSpecial]} {
    $_net setSpecial
  }
}

pin_access

set route_guide $blkname.route_guide
global_route -guide_file $route_guide \
  -congestion_iterations 5 -allow_congestion -verbose

################################################################
# Repair antennas post-GRT

utl::set_metrics_stage "grt__{}"
repair_antennas -iterations 5 -allow_congestion

check_antennas
utl::clear_metrics_stage
utl::metric "GRT::ANT::errors" [ant::antenna_violation_count]

################################################################
# Detailed routing

# Run pin access again after inserting diodes and moving cells
# pin_access

detailed_route -output_drc rpt/route_drc.rpt \
  -output_maze log/maze.log \
  -no_pin_access \
  -droute_end_iter 5 \
  -verbose 1

write_guides $blkname.output_guide.mod
set drv_count [detailed_route_num_drvs]
utl::metric "DRT::drv" $drv_count

g2_openroad_rpt
g2_openroad_out

if {$fvar(sw_exit) eq "1"} {
  exit
}
