set vars(WxH)                                "450umx450um"
set vars(blkname)                            "spi_device"
set vars(depth)                              "3"
set vars(g2module)                           "spec-blk"
set vars(inst_count)                         "20000"
set vars(level)                              "3"
set vars(lim/mem)                            "{fakeram45_1024x32 : v01} {fakeram45_128x32 : v01}"
set vars(lim/stdcell)                        "{sky130_fd_sc_hd : v0.0.2} {sky130_fd_sc_hdll : v0.0.2}"
set vars(main_clock)                         "clk_i"
set vars(pagename)                           "spi_device"
set vars(speed)                              "24MHz"
set vars(view)                               "PPA"
